[build]
  command = "NITRO_PRESET=netlify npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  NITRO_PRESET = "netlify"
  VITE_SUPABASE_URL = "https://xmpyechygwuhewpkceha.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtcHllY2h5Z3d1aGV3cGtjZWhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA0MDM4NzEsImV4cCI6MjEwNTk3OTg3MX0.GATTJEu5MkplaToinkGqOFeYzm-UncU4_EyxuqGGnoU"
