/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SalesManagerRouteImport } from './routes/sales-manager'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as MarketingIndexRouteImport } from './routes/marketing.index'
import { Route as MarketingActionsRouteImport } from './routes/marketing.actions'
import { Route as MarketingAssignmentRouteImport } from './routes/marketing.assignment'
import { Route as MarketingAudioRouteImport } from './routes/marketing.audio'
import { Route as MarketingAuditRouteImport } from './routes/marketing.audit'
import { Route as MarketingCalendarRouteImport } from './routes/marketing.calendar'
import { Route as MarketingCampaignsRouteImport } from './routes/marketing.campaigns'
import { Route as MarketingCopilotRouteImport } from './routes/marketing.copilot'
import { Route as MarketingDashboardRouteImport } from './routes/marketing.dashboard'
import { Route as MarketingInputsRouteImport } from './routes/marketing.inputs'
import { Route as MarketingNotificationsRouteImport } from './routes/marketing.notifications'
import { Route as MarketingPerformanceRouteImport } from './routes/marketing.performance'
import { Route as MarketingPitchExtractionRouteImport } from './routes/marketing.pitch-extraction'
import { Route as MarketingPitchesRouteImport } from './routes/marketing.pitches'
import { Route as MarketingProductsRouteImport } from './routes/marketing.products'
import { Route as MarketingPublishRouteImport } from './routes/marketing.publish'
import { Route as MarketingReportsRouteImport } from './routes/marketing.reports'
import { Route as MarketingVocabularyRouteImport } from './routes/marketing.vocabulary'
import { Route as MarketingVocabularyReviewRouteImport } from './routes/marketing.vocabulary-review'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as ResultsIndexRouteImport } from './routes/results.index'
import { Route as ResultsProgressRouteImport } from './routes/results.progress'
import { Route as SalesIndexRouteImport } from './routes/sales.index'
import { Route as SalesCoachingRouteImport } from './routes/sales.coaching'
import { Route as SalesDashboardRouteImport } from './routes/sales.dashboard'
import { Route as SalesInputsRouteImport } from './routes/sales.inputs'
import { Route as SalesLowPerformersRouteImport } from './routes/sales.low-performers'
import { Route as SalesNotificationsRouteImport } from './routes/sales.notifications'
import { Route as SalesReadinessRouteImport } from './routes/sales.readiness'
import { Route as SalesReportsRouteImport } from './routes/sales.reports'
import { Route as SalesReviewsRouteImport } from './routes/sales.reviews'
import { Route as SalesTeamRouteImport } from './routes/sales.team'
import { Route as CampaignsCampaignIdIndexRouteImport } from './routes/campaigns.$campaignId.index'
import { Route as CampaignsCampaignIdAudioRouteImport } from './routes/campaigns.$campaignId.audio'
import { Route as CampaignsCampaignIdLearningRouteImport } from './routes/campaigns.$campaignId.learning'
import { Route as PracticeCampaignIdIndexRouteImport } from './routes/practice.$campaignId.index'
import { Route as PracticeCampaignIdRecordRouteImport } from './routes/practice.$campaignId.record'
import { Route as PracticeCampaignIdTranscriptRouteImport } from './routes/practice.$campaignId.transcript'
import { Route as ResultsCampaignIdLatestRouteImport } from './routes/results.$campaignId.latest'
import { Route as SalesTmIndexRouteImport } from './routes/sales.tm.index'
import { Route as SalesTmTmIdRouteImport } from './routes/sales.tm.$tmId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesManagerRoute = SalesManagerRouteImport.update({
  id: '/sales-manager',
  path: '/sales-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/admin/campaigns',
  path: '/admin/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/admin/security',
  path: '/admin/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/admin/tenants',
  path: '/admin/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/marketing/',
  path: '/marketing/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingActionsRoute = MarketingActionsRouteImport.update({
  id: '/marketing/actions',
  path: '/marketing/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingAssignmentRoute = MarketingAssignmentRouteImport.update({
  id: '/marketing/assignment',
  path: '/marketing/assignment',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingAudioRoute = MarketingAudioRouteImport.update({
  id: '/marketing/audio',
  path: '/marketing/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingAuditRoute = MarketingAuditRouteImport.update({
  id: '/marketing/audit',
  path: '/marketing/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingCalendarRoute = MarketingCalendarRouteImport.update({
  id: '/marketing/calendar',
  path: '/marketing/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingCampaignsRoute = MarketingCampaignsRouteImport.update({
  id: '/marketing/campaigns',
  path: '/marketing/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingCopilotRoute = MarketingCopilotRouteImport.update({
  id: '/marketing/copilot',
  path: '/marketing/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingDashboardRoute = MarketingDashboardRouteImport.update({
  id: '/marketing/dashboard',
  path: '/marketing/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingInputsRoute = MarketingInputsRouteImport.update({
  id: '/marketing/inputs',
  path: '/marketing/inputs',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingNotificationsRoute = MarketingNotificationsRouteImport.update({
  id: '/marketing/notifications',
  path: '/marketing/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingPerformanceRoute = MarketingPerformanceRouteImport.update({
  id: '/marketing/performance',
  path: '/marketing/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingPitchExtractionRoute =
  MarketingPitchExtractionRouteImport.update({
    id: '/marketing/pitch-extraction',
    path: '/marketing/pitch-extraction',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketingPitchesRoute = MarketingPitchesRouteImport.update({
  id: '/marketing/pitches',
  path: '/marketing/pitches',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingProductsRoute = MarketingProductsRouteImport.update({
  id: '/marketing/products',
  path: '/marketing/products',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingPublishRoute = MarketingPublishRouteImport.update({
  id: '/marketing/publish',
  path: '/marketing/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingReportsRoute = MarketingReportsRouteImport.update({
  id: '/marketing/reports',
  path: '/marketing/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingVocabularyRoute = MarketingVocabularyRouteImport.update({
  id: '/marketing/vocabulary',
  path: '/marketing/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingVocabularyReviewRoute =
  MarketingVocabularyReviewRouteImport.update({
    id: '/marketing/vocabulary-review',
    path: '/marketing/vocabulary-review',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIndexRoute = ResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsProgressRoute = ResultsProgressRouteImport.update({
  id: '/results/progress',
  path: '/results/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCoachingRoute = SalesCoachingRouteImport.update({
  id: '/sales/coaching',
  path: '/sales/coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesDashboardRoute = SalesDashboardRouteImport.update({
  id: '/sales/dashboard',
  path: '/sales/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesInputsRoute = SalesInputsRouteImport.update({
  id: '/sales/inputs',
  path: '/sales/inputs',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesLowPerformersRoute = SalesLowPerformersRouteImport.update({
  id: '/sales/low-performers',
  path: '/sales/low-performers',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesNotificationsRoute = SalesNotificationsRouteImport.update({
  id: '/sales/notifications',
  path: '/sales/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesReadinessRoute = SalesReadinessRouteImport.update({
  id: '/sales/readiness',
  path: '/sales/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesReportsRoute = SalesReportsRouteImport.update({
  id: '/sales/reports',
  path: '/sales/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesReviewsRoute = SalesReviewsRouteImport.update({
  id: '/sales/reviews',
  path: '/sales/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesTeamRoute = SalesTeamRouteImport.update({
  id: '/sales/team',
  path: '/sales/team',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdIndexRoute =
  CampaignsCampaignIdIndexRouteImport.update({
    id: '/campaigns/$campaignId/',
    path: '/campaigns/$campaignId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignIdAudioRoute =
  CampaignsCampaignIdAudioRouteImport.update({
    id: '/campaigns/$campaignId/audio',
    path: '/campaigns/$campaignId/audio',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignIdLearningRoute =
  CampaignsCampaignIdLearningRouteImport.update({
    id: '/campaigns/$campaignId/learning',
    path: '/campaigns/$campaignId/learning',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeCampaignIdIndexRoute = PracticeCampaignIdIndexRouteImport.update({
  id: '/practice/$campaignId/',
  path: '/practice/$campaignId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeCampaignIdRecordRoute =
  PracticeCampaignIdRecordRouteImport.update({
    id: '/practice/$campaignId/record',
    path: '/practice/$campaignId/record',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeCampaignIdTranscriptRoute =
  PracticeCampaignIdTranscriptRouteImport.update({
    id: '/practice/$campaignId/transcript',
    path: '/practice/$campaignId/transcript',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResultsCampaignIdLatestRoute = ResultsCampaignIdLatestRouteImport.update({
  id: '/results/$campaignId/latest',
  path: '/results/$campaignId/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesTmIndexRoute = SalesTmIndexRouteImport.update({
  id: '/sales/tm/',
  path: '/sales/tm/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesTmTmIdRoute = SalesTmTmIdRouteImport.update({
  id: '/sales/tm/$tmId',
  path: '/sales/tm/$tmId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/sales-manager': typeof SalesManagerRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/marketing/actions': typeof MarketingActionsRoute
  '/marketing/assignment': typeof MarketingAssignmentRoute
  '/marketing/audio': typeof MarketingAudioRoute
  '/marketing/audit': typeof MarketingAuditRoute
  '/marketing/calendar': typeof MarketingCalendarRoute
  '/marketing/campaigns': typeof MarketingCampaignsRoute
  '/marketing/copilot': typeof MarketingCopilotRoute
  '/marketing/dashboard': typeof MarketingDashboardRoute
  '/marketing/inputs': typeof MarketingInputsRoute
  '/marketing/notifications': typeof MarketingNotificationsRoute
  '/marketing/performance': typeof MarketingPerformanceRoute
  '/marketing/pitch-extraction': typeof MarketingPitchExtractionRoute
  '/marketing/pitches': typeof MarketingPitchesRoute
  '/marketing/products': typeof MarketingProductsRoute
  '/marketing/publish': typeof MarketingPublishRoute
  '/marketing/reports': typeof MarketingReportsRoute
  '/marketing/vocabulary': typeof MarketingVocabularyRoute
  '/marketing/vocabulary-review': typeof MarketingVocabularyReviewRoute
  '/results/progress': typeof ResultsProgressRoute
  '/sales/coaching': typeof SalesCoachingRoute
  '/sales/dashboard': typeof SalesDashboardRoute
  '/sales/inputs': typeof SalesInputsRoute
  '/sales/low-performers': typeof SalesLowPerformersRoute
  '/sales/notifications': typeof SalesNotificationsRoute
  '/sales/readiness': typeof SalesReadinessRoute
  '/sales/reports': typeof SalesReportsRoute
  '/sales/reviews': typeof SalesReviewsRoute
  '/sales/team': typeof SalesTeamRoute
  '/admin/': typeof AdminIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/marketing/': typeof MarketingIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/results/': typeof ResultsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/campaigns/$campaignId/audio': typeof CampaignsCampaignIdAudioRoute
  '/campaigns/$campaignId/learning': typeof CampaignsCampaignIdLearningRoute
  '/practice/$campaignId/record': typeof PracticeCampaignIdRecordRoute
  '/practice/$campaignId/transcript': typeof PracticeCampaignIdTranscriptRoute
  '/results/$campaignId/latest': typeof ResultsCampaignIdLatestRoute
  '/sales/tm/$tmId': typeof SalesTmTmIdRoute
  '/campaigns/$campaignId/': typeof CampaignsCampaignIdIndexRoute
  '/practice/$campaignId/': typeof PracticeCampaignIdIndexRoute
  '/sales/tm/': typeof SalesTmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/sales-manager': typeof SalesManagerRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/marketing/actions': typeof MarketingActionsRoute
  '/marketing/assignment': typeof MarketingAssignmentRoute
  '/marketing/audio': typeof MarketingAudioRoute
  '/marketing/audit': typeof MarketingAuditRoute
  '/marketing/calendar': typeof MarketingCalendarRoute
  '/marketing/campaigns': typeof MarketingCampaignsRoute
  '/marketing/copilot': typeof MarketingCopilotRoute
  '/marketing/dashboard': typeof MarketingDashboardRoute
  '/marketing/inputs': typeof MarketingInputsRoute
  '/marketing/notifications': typeof MarketingNotificationsRoute
  '/marketing/performance': typeof MarketingPerformanceRoute
  '/marketing/pitch-extraction': typeof MarketingPitchExtractionRoute
  '/marketing/pitches': typeof MarketingPitchesRoute
  '/marketing/products': typeof MarketingProductsRoute
  '/marketing/publish': typeof MarketingPublishRoute
  '/marketing/reports': typeof MarketingReportsRoute
  '/marketing/vocabulary': typeof MarketingVocabularyRoute
  '/marketing/vocabulary-review': typeof MarketingVocabularyReviewRoute
  '/results/progress': typeof ResultsProgressRoute
  '/sales/coaching': typeof SalesCoachingRoute
  '/sales/dashboard': typeof SalesDashboardRoute
  '/sales/inputs': typeof SalesInputsRoute
  '/sales/low-performers': typeof SalesLowPerformersRoute
  '/sales/notifications': typeof SalesNotificationsRoute
  '/sales/readiness': typeof SalesReadinessRoute
  '/sales/reports': typeof SalesReportsRoute
  '/sales/reviews': typeof SalesReviewsRoute
  '/sales/team': typeof SalesTeamRoute
  '/admin': typeof AdminIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/marketing': typeof MarketingIndexRoute
  '/practice': typeof PracticeIndexRoute
  '/results': typeof ResultsIndexRoute
  '/sales': typeof SalesIndexRoute
  '/campaigns/$campaignId/audio': typeof CampaignsCampaignIdAudioRoute
  '/campaigns/$campaignId/learning': typeof CampaignsCampaignIdLearningRoute
  '/practice/$campaignId/record': typeof PracticeCampaignIdRecordRoute
  '/practice/$campaignId/transcript': typeof PracticeCampaignIdTranscriptRoute
  '/results/$campaignId/latest': typeof ResultsCampaignIdLatestRoute
  '/sales/tm/$tmId': typeof SalesTmTmIdRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdIndexRoute
  '/practice/$campaignId': typeof PracticeCampaignIdIndexRoute
  '/sales/tm': typeof SalesTmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/sales-manager': typeof SalesManagerRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/marketing/actions': typeof MarketingActionsRoute
  '/marketing/assignment': typeof MarketingAssignmentRoute
  '/marketing/audio': typeof MarketingAudioRoute
  '/marketing/audit': typeof MarketingAuditRoute
  '/marketing/calendar': typeof MarketingCalendarRoute
  '/marketing/campaigns': typeof MarketingCampaignsRoute
  '/marketing/copilot': typeof MarketingCopilotRoute
  '/marketing/dashboard': typeof MarketingDashboardRoute
  '/marketing/inputs': typeof MarketingInputsRoute
  '/marketing/notifications': typeof MarketingNotificationsRoute
  '/marketing/performance': typeof MarketingPerformanceRoute
  '/marketing/pitch-extraction': typeof MarketingPitchExtractionRoute
  '/marketing/pitches': typeof MarketingPitchesRoute
  '/marketing/products': typeof MarketingProductsRoute
  '/marketing/publish': typeof MarketingPublishRoute
  '/marketing/reports': typeof MarketingReportsRoute
  '/marketing/vocabulary': typeof MarketingVocabularyRoute
  '/marketing/vocabulary-review': typeof MarketingVocabularyReviewRoute
  '/results/progress': typeof ResultsProgressRoute
  '/sales/coaching': typeof SalesCoachingRoute
  '/sales/dashboard': typeof SalesDashboardRoute
  '/sales/inputs': typeof SalesInputsRoute
  '/sales/low-performers': typeof SalesLowPerformersRoute
  '/sales/notifications': typeof SalesNotificationsRoute
  '/sales/readiness': typeof SalesReadinessRoute
  '/sales/reports': typeof SalesReportsRoute
  '/sales/reviews': typeof SalesReviewsRoute
  '/sales/team': typeof SalesTeamRoute
  '/admin/': typeof AdminIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/marketing/': typeof MarketingIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/results/': typeof ResultsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/campaigns/$campaignId/audio': typeof CampaignsCampaignIdAudioRoute
  '/campaigns/$campaignId/learning': typeof CampaignsCampaignIdLearningRoute
  '/practice/$campaignId/record': typeof PracticeCampaignIdRecordRoute
  '/practice/$campaignId/transcript': typeof PracticeCampaignIdTranscriptRoute
  '/results/$campaignId/latest': typeof ResultsCampaignIdLatestRoute
  '/sales/tm/$tmId': typeof SalesTmTmIdRoute
  '/campaigns/$campaignId/': typeof CampaignsCampaignIdIndexRoute
  '/practice/$campaignId/': typeof PracticeCampaignIdIndexRoute
  '/sales/tm/': typeof SalesTmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/sales-manager'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/campaigns'
    | '/admin/dashboard'
    | '/admin/products'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/tenants'
    | '/admin/users'
    | '/marketing/actions'
    | '/marketing/assignment'
    | '/marketing/audio'
    | '/marketing/audit'
    | '/marketing/calendar'
    | '/marketing/campaigns'
    | '/marketing/copilot'
    | '/marketing/dashboard'
    | '/marketing/inputs'
    | '/marketing/notifications'
    | '/marketing/performance'
    | '/marketing/pitch-extraction'
    | '/marketing/pitches'
    | '/marketing/products'
    | '/marketing/publish'
    | '/marketing/reports'
    | '/marketing/vocabulary'
    | '/marketing/vocabulary-review'
    | '/results/progress'
    | '/sales/coaching'
    | '/sales/dashboard'
    | '/sales/inputs'
    | '/sales/low-performers'
    | '/sales/notifications'
    | '/sales/readiness'
    | '/sales/reports'
    | '/sales/reviews'
    | '/sales/team'
    | '/admin/'
    | '/campaigns/'
    | '/marketing/'
    | '/practice/'
    | '/results/'
    | '/sales/'
    | '/campaigns/$campaignId/audio'
    | '/campaigns/$campaignId/learning'
    | '/practice/$campaignId/record'
    | '/practice/$campaignId/transcript'
    | '/results/$campaignId/latest'
    | '/sales/tm/$tmId'
    | '/campaigns/$campaignId/'
    | '/practice/$campaignId/'
    | '/sales/tm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/sales-manager'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/campaigns'
    | '/admin/dashboard'
    | '/admin/products'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/tenants'
    | '/admin/users'
    | '/marketing/actions'
    | '/marketing/assignment'
    | '/marketing/audio'
    | '/marketing/audit'
    | '/marketing/calendar'
    | '/marketing/campaigns'
    | '/marketing/copilot'
    | '/marketing/dashboard'
    | '/marketing/inputs'
    | '/marketing/notifications'
    | '/marketing/performance'
    | '/marketing/pitch-extraction'
    | '/marketing/pitches'
    | '/marketing/products'
    | '/marketing/publish'
    | '/marketing/reports'
    | '/marketing/vocabulary'
    | '/marketing/vocabulary-review'
    | '/results/progress'
    | '/sales/coaching'
    | '/sales/dashboard'
    | '/sales/inputs'
    | '/sales/low-performers'
    | '/sales/notifications'
    | '/sales/readiness'
    | '/sales/reports'
    | '/sales/reviews'
    | '/sales/team'
    | '/admin'
    | '/campaigns'
    | '/marketing'
    | '/practice'
    | '/results'
    | '/sales'
    | '/campaigns/$campaignId/audio'
    | '/campaigns/$campaignId/learning'
    | '/practice/$campaignId/record'
    | '/practice/$campaignId/transcript'
    | '/results/$campaignId/latest'
    | '/sales/tm/$tmId'
    | '/campaigns/$campaignId'
    | '/practice/$campaignId'
    | '/sales/tm'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/sales-manager'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/campaigns'
    | '/admin/dashboard'
    | '/admin/products'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/tenants'
    | '/admin/users'
    | '/marketing/actions'
    | '/marketing/assignment'
    | '/marketing/audio'
    | '/marketing/audit'
    | '/marketing/calendar'
    | '/marketing/campaigns'
    | '/marketing/copilot'
    | '/marketing/dashboard'
    | '/marketing/inputs'
    | '/marketing/notifications'
    | '/marketing/performance'
    | '/marketing/pitch-extraction'
    | '/marketing/pitches'
    | '/marketing/products'
    | '/marketing/publish'
    | '/marketing/reports'
    | '/marketing/vocabulary'
    | '/marketing/vocabulary-review'
    | '/results/progress'
    | '/sales/coaching'
    | '/sales/dashboard'
    | '/sales/inputs'
    | '/sales/low-performers'
    | '/sales/notifications'
    | '/sales/readiness'
    | '/sales/reports'
    | '/sales/reviews'
    | '/sales/team'
    | '/admin/'
    | '/campaigns/'
    | '/marketing/'
    | '/practice/'
    | '/results/'
    | '/sales/'
    | '/campaigns/$campaignId/audio'
    | '/campaigns/$campaignId/learning'
    | '/practice/$campaignId/record'
    | '/practice/$campaignId/transcript'
    | '/results/$campaignId/latest'
    | '/sales/tm/$tmId'
    | '/campaigns/$campaignId/'
    | '/practice/$campaignId/'
    | '/sales/tm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SalesManagerRoute: typeof SalesManagerRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  MarketingActionsRoute: typeof MarketingActionsRoute
  MarketingAssignmentRoute: typeof MarketingAssignmentRoute
  MarketingAudioRoute: typeof MarketingAudioRoute
  MarketingAuditRoute: typeof MarketingAuditRoute
  MarketingCalendarRoute: typeof MarketingCalendarRoute
  MarketingCampaignsRoute: typeof MarketingCampaignsRoute
  MarketingCopilotRoute: typeof MarketingCopilotRoute
  MarketingDashboardRoute: typeof MarketingDashboardRoute
  MarketingInputsRoute: typeof MarketingInputsRoute
  MarketingNotificationsRoute: typeof MarketingNotificationsRoute
  MarketingPerformanceRoute: typeof MarketingPerformanceRoute
  MarketingPitchExtractionRoute: typeof MarketingPitchExtractionRoute
  MarketingPitchesRoute: typeof MarketingPitchesRoute
  MarketingProductsRoute: typeof MarketingProductsRoute
  MarketingPublishRoute: typeof MarketingPublishRoute
  MarketingReportsRoute: typeof MarketingReportsRoute
  MarketingVocabularyRoute: typeof MarketingVocabularyRoute
  MarketingVocabularyReviewRoute: typeof MarketingVocabularyReviewRoute
  ResultsProgressRoute: typeof ResultsProgressRoute
  SalesCoachingRoute: typeof SalesCoachingRoute
  SalesDashboardRoute: typeof SalesDashboardRoute
  SalesInputsRoute: typeof SalesInputsRoute
  SalesLowPerformersRoute: typeof SalesLowPerformersRoute
  SalesNotificationsRoute: typeof SalesNotificationsRoute
  SalesReadinessRoute: typeof SalesReadinessRoute
  SalesReportsRoute: typeof SalesReportsRoute
  SalesReviewsRoute: typeof SalesReviewsRoute
  SalesTeamRoute: typeof SalesTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
  ResultsIndexRoute: typeof ResultsIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
  CampaignsCampaignIdAudioRoute: typeof CampaignsCampaignIdAudioRoute
  CampaignsCampaignIdLearningRoute: typeof CampaignsCampaignIdLearningRoute
  PracticeCampaignIdRecordRoute: typeof PracticeCampaignIdRecordRoute
  PracticeCampaignIdTranscriptRoute: typeof PracticeCampaignIdTranscriptRoute
  ResultsCampaignIdLatestRoute: typeof ResultsCampaignIdLatestRoute
  SalesTmTmIdRoute: typeof SalesTmTmIdRoute
  CampaignsCampaignIdIndexRoute: typeof CampaignsCampaignIdIndexRoute
  PracticeCampaignIdIndexRoute: typeof PracticeCampaignIdIndexRoute
  SalesTmIndexRoute: typeof SalesTmIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-manager': {
      id: '/sales-manager'
      path: '/sales-manager'
      fullPath: '/sales-manager'
      preLoaderRoute: typeof SalesManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/admin/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/': {
      id: '/marketing/'
      path: '/marketing'
      fullPath: '/marketing/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/actions': {
      id: '/marketing/actions'
      path: '/marketing/actions'
      fullPath: '/marketing/actions'
      preLoaderRoute: typeof MarketingActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/assignment': {
      id: '/marketing/assignment'
      path: '/marketing/assignment'
      fullPath: '/marketing/assignment'
      preLoaderRoute: typeof MarketingAssignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/audio': {
      id: '/marketing/audio'
      path: '/marketing/audio'
      fullPath: '/marketing/audio'
      preLoaderRoute: typeof MarketingAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/audit': {
      id: '/marketing/audit'
      path: '/marketing/audit'
      fullPath: '/marketing/audit'
      preLoaderRoute: typeof MarketingAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/calendar': {
      id: '/marketing/calendar'
      path: '/marketing/calendar'
      fullPath: '/marketing/calendar'
      preLoaderRoute: typeof MarketingCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/campaigns': {
      id: '/marketing/campaigns'
      path: '/marketing/campaigns'
      fullPath: '/marketing/campaigns'
      preLoaderRoute: typeof MarketingCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/copilot': {
      id: '/marketing/copilot'
      path: '/marketing/copilot'
      fullPath: '/marketing/copilot'
      preLoaderRoute: typeof MarketingCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/dashboard': {
      id: '/marketing/dashboard'
      path: '/marketing/dashboard'
      fullPath: '/marketing/dashboard'
      preLoaderRoute: typeof MarketingDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/inputs': {
      id: '/marketing/inputs'
      path: '/marketing/inputs'
      fullPath: '/marketing/inputs'
      preLoaderRoute: typeof MarketingInputsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/notifications': {
      id: '/marketing/notifications'
      path: '/marketing/notifications'
      fullPath: '/marketing/notifications'
      preLoaderRoute: typeof MarketingNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/performance': {
      id: '/marketing/performance'
      path: '/marketing/performance'
      fullPath: '/marketing/performance'
      preLoaderRoute: typeof MarketingPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/pitch-extraction': {
      id: '/marketing/pitch-extraction'
      path: '/marketing/pitch-extraction'
      fullPath: '/marketing/pitch-extraction'
      preLoaderRoute: typeof MarketingPitchExtractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/pitches': {
      id: '/marketing/pitches'
      path: '/marketing/pitches'
      fullPath: '/marketing/pitches'
      preLoaderRoute: typeof MarketingPitchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/products': {
      id: '/marketing/products'
      path: '/marketing/products'
      fullPath: '/marketing/products'
      preLoaderRoute: typeof MarketingProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/publish': {
      id: '/marketing/publish'
      path: '/marketing/publish'
      fullPath: '/marketing/publish'
      preLoaderRoute: typeof MarketingPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/reports': {
      id: '/marketing/reports'
      path: '/marketing/reports'
      fullPath: '/marketing/reports'
      preLoaderRoute: typeof MarketingReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/vocabulary': {
      id: '/marketing/vocabulary'
      path: '/marketing/vocabulary'
      fullPath: '/marketing/vocabulary'
      preLoaderRoute: typeof MarketingVocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/vocabulary-review': {
      id: '/marketing/vocabulary-review'
      path: '/marketing/vocabulary-review'
      fullPath: '/marketing/vocabulary-review'
      preLoaderRoute: typeof MarketingVocabularyReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/': {
      id: '/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof ResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/progress': {
      id: '/results/progress'
      path: '/results/progress'
      fullPath: '/results/progress'
      preLoaderRoute: typeof ResultsProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/coaching': {
      id: '/sales/coaching'
      path: '/sales/coaching'
      fullPath: '/sales/coaching'
      preLoaderRoute: typeof SalesCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/dashboard': {
      id: '/sales/dashboard'
      path: '/sales/dashboard'
      fullPath: '/sales/dashboard'
      preLoaderRoute: typeof SalesDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/inputs': {
      id: '/sales/inputs'
      path: '/sales/inputs'
      fullPath: '/sales/inputs'
      preLoaderRoute: typeof SalesInputsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/low-performers': {
      id: '/sales/low-performers'
      path: '/sales/low-performers'
      fullPath: '/sales/low-performers'
      preLoaderRoute: typeof SalesLowPerformersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/notifications': {
      id: '/sales/notifications'
      path: '/sales/notifications'
      fullPath: '/sales/notifications'
      preLoaderRoute: typeof SalesNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/readiness': {
      id: '/sales/readiness'
      path: '/sales/readiness'
      fullPath: '/sales/readiness'
      preLoaderRoute: typeof SalesReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/reports': {
      id: '/sales/reports'
      path: '/sales/reports'
      fullPath: '/sales/reports'
      preLoaderRoute: typeof SalesReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/reviews': {
      id: '/sales/reviews'
      path: '/sales/reviews'
      fullPath: '/sales/reviews'
      preLoaderRoute: typeof SalesReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/team': {
      id: '/sales/team'
      path: '/sales/team'
      fullPath: '/sales/team'
      preLoaderRoute: typeof SalesTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/': {
      id: '/campaigns/$campaignId/'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId/'
      preLoaderRoute: typeof CampaignsCampaignIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/audio': {
      id: '/campaigns/$campaignId/audio'
      path: '/campaigns/$campaignId/audio'
      fullPath: '/campaigns/$campaignId/audio'
      preLoaderRoute: typeof CampaignsCampaignIdAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/learning': {
      id: '/campaigns/$campaignId/learning'
      path: '/campaigns/$campaignId/learning'
      fullPath: '/campaigns/$campaignId/learning'
      preLoaderRoute: typeof CampaignsCampaignIdLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$campaignId/': {
      id: '/practice/$campaignId/'
      path: '/practice/$campaignId'
      fullPath: '/practice/$campaignId/'
      preLoaderRoute: typeof PracticeCampaignIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$campaignId/record': {
      id: '/practice/$campaignId/record'
      path: '/practice/$campaignId/record'
      fullPath: '/practice/$campaignId/record'
      preLoaderRoute: typeof PracticeCampaignIdRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$campaignId/transcript': {
      id: '/practice/$campaignId/transcript'
      path: '/practice/$campaignId/transcript'
      fullPath: '/practice/$campaignId/transcript'
      preLoaderRoute: typeof PracticeCampaignIdTranscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$campaignId/latest': {
      id: '/results/$campaignId/latest'
      path: '/results/$campaignId/latest'
      fullPath: '/results/$campaignId/latest'
      preLoaderRoute: typeof ResultsCampaignIdLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/tm/': {
      id: '/sales/tm/'
      path: '/sales/tm'
      fullPath: '/sales/tm/'
      preLoaderRoute: typeof SalesTmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/tm/$tmId': {
      id: '/sales/tm/$tmId'
      path: '/sales/tm/$tmId'
      fullPath: '/sales/tm/$tmId'
      preLoaderRoute: typeof SalesTmTmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SalesManagerRoute: SalesManagerRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminUsersRoute: AdminUsersRoute,
  MarketingActionsRoute: MarketingActionsRoute,
  MarketingAssignmentRoute: MarketingAssignmentRoute,
  MarketingAudioRoute: MarketingAudioRoute,
  MarketingAuditRoute: MarketingAuditRoute,
  MarketingCalendarRoute: MarketingCalendarRoute,
  MarketingCampaignsRoute: MarketingCampaignsRoute,
  MarketingCopilotRoute: MarketingCopilotRoute,
  MarketingDashboardRoute: MarketingDashboardRoute,
  MarketingInputsRoute: MarketingInputsRoute,
  MarketingNotificationsRoute: MarketingNotificationsRoute,
  MarketingPerformanceRoute: MarketingPerformanceRoute,
  MarketingPitchExtractionRoute: MarketingPitchExtractionRoute,
  MarketingPitchesRoute: MarketingPitchesRoute,
  MarketingProductsRoute: MarketingProductsRoute,
  MarketingPublishRoute: MarketingPublishRoute,
  MarketingReportsRoute: MarketingReportsRoute,
  MarketingVocabularyRoute: MarketingVocabularyRoute,
  MarketingVocabularyReviewRoute: MarketingVocabularyReviewRoute,
  ResultsProgressRoute: ResultsProgressRoute,
  SalesCoachingRoute: SalesCoachingRoute,
  SalesDashboardRoute: SalesDashboardRoute,
  SalesInputsRoute: SalesInputsRoute,
  SalesLowPerformersRoute: SalesLowPerformersRoute,
  SalesNotificationsRoute: SalesNotificationsRoute,
  SalesReadinessRoute: SalesReadinessRoute,
  SalesReportsRoute: SalesReportsRoute,
  SalesReviewsRoute: SalesReviewsRoute,
  SalesTeamRoute: SalesTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  PracticeIndexRoute: PracticeIndexRoute,
  ResultsIndexRoute: ResultsIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
  CampaignsCampaignIdAudioRoute: CampaignsCampaignIdAudioRoute,
  CampaignsCampaignIdLearningRoute: CampaignsCampaignIdLearningRoute,
  PracticeCampaignIdRecordRoute: PracticeCampaignIdRecordRoute,
  PracticeCampaignIdTranscriptRoute: PracticeCampaignIdTranscriptRoute,
  ResultsCampaignIdLatestRoute: ResultsCampaignIdLatestRoute,
  SalesTmTmIdRoute: SalesTmTmIdRoute,
  CampaignsCampaignIdIndexRoute: CampaignsCampaignIdIndexRoute,
  PracticeCampaignIdIndexRoute: PracticeCampaignIdIndexRoute,
  SalesTmIndexRoute: SalesTmIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
